### ISSUE TITLE
Swarm ...

### ISSUE THREAD

**Issue by kotamahesh** [flaccid/docker-docker-gc-crond#1]
Hi 

should I run this command for removing images and containers that are not in use as service in swarm.

EXAMPLE: garbage as service name:

docker service create \
  --mode global \
  --name=garbage \

flaccid/docker-gc-crond
  

please let me know should I make any changes in command ?I think this will remove all images and containers in swarm.

**Comment by kotamahesh** [comment]
???

**Comment by kotamahesh** [comment]
I think this doesnot work for swarm ...

**Comment by flaccid** [comment]
People still use swarm?

**Comment by kotamahesh** [comment]
yes we are still using swarm ?? can u tell me how this image should work in swarm in removing all containers and images as service.

**Comment by kotamahesh** [comment]
should we run each container on differnt nodes ?? or any other apporach ...

**Comment by kotamahesh** [comment]
i solved my self ....
